Repository ucsb-cs148-w25/pj08-studytimer, pull requests merged in 2025-01, with the labels that each got.

#8 Created the Norms File
  team/NORMS.md
Labels: Lab01

#13 Lawrence Wang Hello World Deployment
  .gitignore
  helloworldapps/lawrence_wang_hello_world/.gitignore
  helloworldapps/lawrence_wang_hello_world/README.md
  helloworldapps/lawrence_wang_hello_world/package-lock.json
  helloworldapps/lawrence_wang_hello_world/package.json
  helloworldapps/lawrence_wang_hello_world/public/favicon.ico
  helloworldapps/lawrence_wang_hello_world/public/index.html
  helloworldapps/lawrence_wang_hello_world/public/logo192.png
  helloworldapps/lawrence_wang_hello_world/public/logo512.png
  helloworldapps/lawrence_wang_hello_world/public/manifest.json
  helloworldapps/lawrence_wang_hello_world/public/robots.txt
  helloworldapps/lawrence_wang_hello_world/src/App.css
  helloworldapps/lawrence_wang_hello_world/src/App.js
  helloworldapps/lawrence_wang_hello_world/src/App.test.js
  helloworldapps/lawrence_wang_hello_world/src/index.css
  helloworldapps/lawrence_wang_hello_world/src/index.js
  helloworldapps/lawrence_wang_hello_world/src/logo.svg
  helloworldapps/lawrence_wang_hello_world/src/reportWebVitals.js
  helloworldapps/lawrence_wang_hello_world/src/setupTests.js
Labels: Hello World

#19 Andrew Hello World Web App
  helloworldapps/andrew_hello_world/.gitignore
  helloworldapps/andrew_hello_world/README.md
  helloworldapps/andrew_hello_world/package-lock.json
  helloworldapps/andrew_hello_world/package.json
  helloworldapps/andrew_hello_world/public/favicon.ico
  helloworldapps/andrew_hello_world/public/index.html
  helloworldapps/andrew_hello_world/public/logo192.png
  helloworldapps/andrew_hello_world/public/logo512.png
  helloworldapps/andrew_hello_world/public/manifest.json
  helloworldapps/andrew_hello_world/public/robots.txt
  helloworldapps/andrew_hello_world/src/App.css
  helloworldapps/andrew_hello_world/src/App.js
  helloworldapps/andrew_hello_world/src/App.test.js
  helloworldapps/andrew_hello_world/src/index.css
  helloworldapps/andrew_hello_world/src/index.js
  helloworldapps/andrew_hello_world/src/logo.svg
  helloworldapps/andrew_hello_world/src/reportWebVitals.js
  helloworldapps/andrew_hello_world/src/setupTests.js
Labels: Hello World

#20 lw - Created LICENSE.md and .gitignore files
  .gitignore
  LICENSE.md
Labels: documentation

#23 Added lab02.md and user_personas.md notes from our previous meetings
  team/sprint01/lab02.md
  team/sprint01/user_personas.md
Labels: documentation

#24 moved thienan hello world to helloworldapps directory
  helloworldapps/thienan_hello_world/.gitignore
  helloworldapps/thienan_hello_world/README.md
  helloworldapps/thienan_hello_world/package-lock.json
  helloworldapps/thienan_hello_world/package.json
  helloworldapps/thienan_hello_world/public/favicon.ico
  helloworldapps/thienan_hello_world/public/index.html
  helloworldapps/thienan_hello_world/public/logo192.png
  helloworldapps/thienan_hello_world/public/logo512.png
  helloworldapps/thienan_hello_world/public/manifest.json
  helloworldapps/thienan_hello_world/public/robots.txt
  helloworldapps/thienan_hello_world/src/App.css
  helloworldapps/thienan_hello_world/src/App.js
  helloworldapps/thienan_hello_world/src/App.test.js
  helloworldapps/thienan_hello_world/src/index.css
  helloworldapps/thienan_hello_world/src/index.js
  helloworldapps/thienan_hello_world/src/logo.svg
  helloworldapps/thienan_hello_world/src/reportWebVitals.js
  helloworldapps/thienan_hello_world/src/setupTests.js
Labels: documentation

#25 Hello World for Lab01
  helloworldapps/edwin-hello-world/.gitignore
  helloworldapps/edwin-hello-world/README.md
  helloworldapps/edwin-hello-world/package-lock.json
  helloworldapps/edwin-hello-world/package.json
  helloworldapps/edwin-hello-world/public/favicon.ico
  helloworldapps/edwin-hello-world/public/index.html
  helloworldapps/edwin-hello-world/public/logo192.png
  helloworldapps/edwin-hello-world/public/logo512.png
  helloworldapps/edwin-hello-world/public/manifest.json
  helloworldapps/edwin-hello-world/public/robots.txt
  helloworldapps/edwin-hello-world/src/App.css
  helloworldapps/edwin-hello-world/src/App.js
  helloworldapps/edwin-hello-world/src/App.test.js
  helloworldapps/edwin-hello-world/src/index.css
  helloworldapps/edwin-hello-world/src/index.js
  helloworldapps/edwin-hello-world/src/logo.svg
  helloworldapps/edwin-hello-world/src/reportWebVitals.js
  helloworldapps/edwin-hello-world/src/setupTests.js
Labels: Hello World

#22 Created hello world demo with React
  helloworldapps/cindy_hello_world/.gitignore
  helloworldapps/cindy_hello_world/README.md
  helloworldapps/cindy_hello_world/package-lock.json
  helloworldapps/cindy_hello_world/package.json
  helloworldapps/cindy_hello_world/public/favicon.ico
  helloworldapps/cindy_hello_world/public/index.html
  helloworldapps/cindy_hello_world/public/logo192.png
  helloworldapps/cindy_hello_world/public/logo512.png
  helloworldapps/cindy_hello_world/public/manifest.json
  helloworldapps/cindy_hello_world/public/robots.txt
  helloworldapps/cindy_hello_world/src/App.css
  helloworldapps/cindy_hello_world/src/App.js
  helloworldapps/cindy_hello_world/src/App.test.js
  helloworldapps/cindy_hello_world/src/index.css
  helloworldapps/cindy_hello_world/src/index.js
  helloworldapps/cindy_hello_world/src/logo.svg
  helloworldapps/cindy_hello_world/src/reportWebVitals.js
  helloworldapps/cindy_hello_world/src/setupTests.js
Labels: Hello World

#26 Updated user_journey and problem_scenario for lab01
  team/problem_scenario.md
  team/user_journey.md
Labels: Documentation

#27 Added .github dir and CODEOWNERS file
  .github/CODEOWNERS
Labels: Enhancement

#28 lw - added lab02-addendum details
  README.md
Labels: Documentation, Lab02

#44 Removed .DS_Store file, Preventing Merge Conflicts
  .DS_Store
Labels: Enhancement

#63 Updated README.md for Project timewise
  README.md
Labels: Documentation, MVP

#62 jl - Added Retrospectives folder + RETRO_01.md file
  team/retrospectives/RETRO_01.md
Labels: Documentation

#79 Removed React Icons & Updated gitignore File
  frontend/timewise/.gitignore
  frontend/timewise/public/logo192.png
  frontend/timewise/public/logo512.png
Labels: Enhancement, Backend

#89 cz - added calendar component
  frontend/timewise/src/App.js
  frontend/timewise/src/components/CalendarEmbed.css
  frontend/timewise/src/components/CalendarEmbed.js
  frontend/timewise/src/components/CalendarPage.css
  frontend/timewise/src/components/CalendarPage.js
  frontend/timewise/src/components/Header.css
  frontend/timewise/src/components/Header.js
  frontend/timewise/src/components/Sidebar.css
  frontend/timewise/src/components/Sidebar.js
Labels: User Story #40

#88 Improved Navbar Similar to Previous Projects in CS148, and my own ideas!
  frontend/package-lock.json
  frontend/package.json
  frontend/timewise/package-lock.json
  frontend/timewise/package.json
  frontend/timewise/src/components/Navbar.js
  frontend/timewise/src/components/NavbarStyles.css
Labels: MVP, Frontend, Backend, User Story #34
