Repository ucsb-cs148-w25/pj08-studytimer, pull requests merged in 2025-03, with the labels that each got.

#169 JL - Updated LEADERSHIP.md
  docs/DESIGN.md
  team/LEADERSHIP.md
Labels: Documentation

#168 kl - only show ucsb.edu emails
  frontend/src/auth.js
Labels: Enhancement

#175 kl - added contributions dir
  team/contributions/CONTRIBS.md
Labels: Documentation

#187 KL - Completed Retro03
  team/contributions/CONTRIBS.md
  team/retrospectives/RETRO_03.md
Labels: Documentation

#191 KL - added example .env
  .env.example
Labels: Documentation

#194 KL - revamped timer to use pomodoro technique
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/Home/BreakTimer.js
  frontend/src/components/Home/PomodoroTimer.css
  frontend/src/components/Home/PomodoroTimer.js
  frontend/src/components/Home/SettingsModal.css
  frontend/src/components/Home/SettingsModal.js
Labels: Enhancement, Frontend

#198 KL - Task Fetch to Calendar
  backend/src/main/java/com/example/timewise/controller/CalendarController.java
  frontend/src/components/Calendar/CalendarEmbed.js
  frontend/src/components/ToDo/TaskBoard.js
  frontend/src/services/CalendarService.js
Labels: Enhancement, Frontend, Backend

#200 KL - Added lab09.md + Updated CONTRIBS.md
  team/contributions/CONTRIBS.md
  team/sprint04/lab09.md
Labels: Documentation

#201 KL - tasks now appear on Google Calendar
  backend/src/main/java/com/example/timewise/controller/CalendarController.java
  backend/src/main/java/com/example/timewise/dto/EventDTO.java
  backend/src/main/java/com/example/timewise/dto/TaskEventDTO.java
  frontend/src/components/Calendar/CalendarEmbed.js
  frontend/src/components/ToDo/TaskList.js
  frontend/src/services/CalendarService.js
Labels: Enhancement, Frontend, Backend

#206 KL - Task lists updates now show up on Google Calendar
  backend/src/main/java/com/example/timewise/controller/CalendarController.java
  frontend/src/components/ToDo/TaskList.js
  frontend/src/components/ToDo/TaskNav.js
  frontend/src/services/CalendarService.js
Labels: Enhancement, Frontend, Backend

#207 KL - Fixed issue with Backend Going to Sleep
  .github/workflows/keep-awake.yml
Labels: Enhancement, Backend

#209 AV - Bug Fix: Friend Requests
  frontend/src/components/Community/Community.css
  frontend/src/components/Community/Community.js
  frontend/src/components/Community/FriendRequestsMenu.js
Labels: Enhancement, Frontend

#210 KL - Update keep-awake.yml
  .github/workflows/keep-awake.yml
Labels: Bug Fix

#211 KL - modified to logout when exiting site due to unreliable cached login
  frontend/src/auth.js
Labels: Frontend, Bug Fix

#212 KL - bug fixes to auto logout
  frontend/src/App.js
  frontend/src/auth.js
Labels: Bug Fix

#214 JL - UI improvements to metrics sidebar + bug fixes
  frontend/src/components/Home/HomeSidebar.js
  frontend/src/components/Profile/MetricsSidebar.css
  frontend/src/components/Profile/MetricsSidebar.js
  frontend/src/components/Profile/Profile.css
  frontend/src/components/Profile/Profile.js
  frontend/src/components/ToDo/MetricsChart.css
  frontend/src/components/ToDo/TaskCalendarChart.js
Labels: Enhancement, Frontend

#215 CZ - Fixed calendar component scroll bug
  frontend/src/components/Calendar/CalendarEmbed.css
  frontend/src/components/Calendar/CalendarPage.css
Labels: Bug Fix

#216 KL - reload no longer signs you out
  frontend/src/App.js
  frontend/src/auth.js
Labels: Bug Fix

#220 CZ - Added standup notes from lect16
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/components/Calendar/CalendarEmbed.css
  frontend/src/components/Calendar/CalendarPage.css
  frontend/src/components/NavBar/Navbar.css
  team/sprint04/lect16.md
Labels: Documentation

#218 KL - updated navbar UI/UX
  frontend/src/components/NavBar/Navbar.css
  frontend/src/components/NavBar/Navbar.js
Labels: Enhancement, Frontend

#219 KL - modified calendar to work with themes
  frontend/src/ThemeStyles.css
  frontend/src/components/Calendar/CalendarEmbed.css
  frontend/src/components/Calendar/CalendarEmbed.js
  frontend/src/components/Calendar/EventDetailsModal.css
Labels: Enhancement, Frontend

#221 LW - Settings Modal visible in Dark theme
  frontend/src/components/AppSettings/Settings.js
  frontend/src/components/Home/PomodoroTimer.css
  frontend/src/components/Home/PomodoroTimer.js
Labels: Enhancement, Frontend

#188 LW - added DEPLOY.md file
  docs/DEPLOY.md
  serviceAccountKey.example.json
Labels: Documentation

#224 KL - Fixed skip button for non-logged in user
  frontend/src/components/Home/PomodoroTimer.js
Labels: Bug Fix

#227 KL - fixed delay on calendar fetch
  frontend/src/App.js
  frontend/src/CalendarContext.js
  frontend/src/components/Calendar/CalendarEmbed.js
Labels: Frontend, Bug Fix

#229 Update About.js
  frontend/src/components/About/About.js
Labels: Bug Fix

#230 KL - added loading screen while calendar events fetch
  frontend/public/index.html
  frontend/src/CalendarContext.js
  frontend/src/ThemeStyles.css
  frontend/src/components/Calendar/CalendarEmbed.css
  frontend/src/components/Calendar/CalendarEmbed.js
Labels: Frontend, Bug Fix

#231 AV - Profile & Community Rework
  frontend/public/icons/calendar.png
  frontend/public/icons/clock.png
  frontend/public/icons/coffee.png
  frontend/public/icons/edit.png
  frontend/public/icons/play.png
  frontend/public/icons/stopwatch.png
  frontend/public/profile-icon.png
  frontend/src/App.css
  frontend/src/ThemeStyles.css
  frontend/src/components/Community/Community.css
  frontend/src/components/NavBar/Navbar.css
  frontend/src/components/Profile/FriendProfile.js
  frontend/src/components/Profile/Profile.css
  frontend/src/components/Profile/Profile.js
  frontend/src/components/ToDo/MetricsChart.css
  frontend/src/components/ToDo/MetricsChart.js
  frontend/src/utils/unlockAchievement.js
Labels: Enhancement, Bug Fix

#232 AV - Updated Minor Color and Spacing Issues
  frontend/src/components/Community/Community.css
  frontend/src/components/Profile/Profile.css
Labels: Enhancement

#234 LW - Timer Persistence
  frontend/src/components/Home/PomodoroTimer.js
Labels: Frontend, Bug Fix

#233 KL - calendar auto fetch newly added tasks
  frontend/src/CalendarContext.js
Labels: Frontend, Bug Fix

#240 KL - fixed all timer bugs
  frontend/src/App.js
  frontend/src/TimerContext.js
  frontend/src/components/Home/PomodoroTimer.js
Labels: Bug Fix

#238 AV - Stats wont reset to 0
  frontend/src/App.js
  frontend/src/components/Home/PomodoroTimer.js
  frontend/src/components/Profile/FriendProfile.js
  frontend/src/components/Profile/Profile.css
  frontend/src/utils/useSyncUserProfile.js
Labels: Bug Fix

#244 KL - fixed scaling on pending tasks
  frontend/src/components/Profile/Profile.css
Labels: Bug Fix

#247 KL - final version of contribs
  team/contributions/CONTRIBS.md
Labels: Documentation

#248 Update CONTRIBS.md Title
  team/contributions/CONTRIBS.md
Labels: Documentation
